version: "3.7"
services:
  fastapi:
    image: fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./app:/code/app
    depends_on:
      - db
  db:
    image: mariadb:latest
    container_name: db
    ports:
      - 3306:3306
    networks:
      - backend
networks:
  - backend